version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "13306:3306"
    networks:
      - "algafood-network"

  algafood-redis:
    image: redis:latest
    networks:
      - "algafood-network"

  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "-t", "30", "algafood-mysql:3306", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_KEYPAIR_ALIAS: ${JWT_KEYPAIR_ALIAS}
      JWT_KEYPAIR_PASSWORD: ${JWT_KEYPAIR_PASSWORD}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY_ID: ${S3_SECRET_ACCESS_KEY_ID}
      LOGGLY_TOKEN: ${LOGGLY_TOKEN}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: development
    networks:
      - "algafood-network"
    depends_on:
      - algafood-mysql

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - "algafood-network"
    depends_on:
      - algafood-api